drop table if exists stats cascade;

create table stats (
    id integer generated by default as identity not null primary key,
    app varchar(256) not null,
    uri varchar(256) not null,
    ip varchar(20) not null,
    time_stat timestamp with time zone not null
);

