version: '3.8'
services:
  stats-server:
    build: stats-service/stats-server
    image: stats-server-image
    container_name: stats-server
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/statsdb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - TZ=Europe/Moscow

  stats-db:
    image: postgres:14-alpine
    container_name: stats-db
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=statsdb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root

  ewm-service:
    build: main-service
    image: ewm-server-image
    container_name: ewm-server
    ports:
      - "8080:8080"
    depends_on:
      - ewm-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/ewmdb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - TZ=Europe/Moscow

  ewm-db:
    image: postgres:14-alpine
    container_name: ewm-db
    ports:
      - "6542:5432"
    environment:
      - POSTGRES_DB=ewmdb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root